### ISSUE TITLE
Sorting algorithms for Lib and Cons Articles

### ISSUE THREAD

**Issue by emanuallan** [emanuallan/WTLT#6]
# TODO:
- [x] Create simple [Express](https://expressjs.com/) API
- [x] Add conservative/liberal sorting algos
- [x] Deploy to some cloud instance
- [x] replace `fetch` requests to news API with requests to our API

**Comment by emanuallan** [comment]
SortBy date needs to be implemented
